### ISSUE TITLE
Crash trying to enter an existing hyperbox

### ISSUE THREAD

**Issue by aburone** [Commoble/hyperbox#5] opened 2021-07-05 05:12 UTC
I haven't gone inside it for several days. Now every time I try to do se. The internal server halts. And I have to kill the Java process.
From debug.log
https://pastebin.pl/view/29e86e58

This is only time it actually crashed the game and got a crash-reppport
https://pastebin.pl/view/a5972ace

**Comment by Commoble** [comment] 2021-07-05 16:57
I haven't been able to reproduce the server halt or the server crash, I suspect the server halt is due to a weird interaction with another mod, but I wouldn't be able to tell which one it is as the mod list is very large.

I should be able to at least prevent the crash from happening, though (fixed in 1.0.0.2). If you can narrow down which mod(s) causes the server halt, then open a new issue report just for the halt

**Closed as completed by Commoble** 2021-07-05 16:57 UTC
